
const categoryData = [
  {
    "category": "IT학부",
    "depts": [
      {
        "name": "IT학부",
        "majors": [
          "컴퓨터공학과",
          "융합보안학과",
          "IT학부"
        ]
      }
    ]
  },
  {
    "category": "디자인학부",
    "depts": [
      {
        "name": "디자인학부",
        "majors": [
          "시각정보디자인학과",
          "실내건축디자인학과",
          "섬유패션디자인학과",
          "디자인학부"
        ]
      }
    ]
  },
  {
    "category": "예술학부",
    "depts": [
      {
        "name": "예술학부",
        "majors": [
          "음악학과",
          "공연예술학과"
        ]
      }
    ]
  },
  {
    "category": "신학과",
    "depts": [
      {
        "name": "신학과",
        "majors": [
          "신학과"
        ]
      }
    ]
  },
  {
    "category": "사회과학부",
    "depts": [
      {
        "name": "사회과학부",
        "majors": [
          "미디어영상광고학과",
          "경영학과",
          "관광경영학과",
        ]
      }
    ]
  },
  {
    "category": "공공서비스학부",
    "depts": [
      {
        "name": "공공서비스학부",
        "majors": [
          "경찰행정학과",
          "사회복지학과"
        ]
      }
    ]
  },
  {
    "category": "언어학부",
    "depts": [
      {
        "name": "언어학부",
        "majors": [
          "영어학과",
          "중국어학과"
        ]
      }
    ]
  },
  {
    "category": "간호학과",
    "depts": [
      {
        "name": "간호학과",
        "majors": [
          "간호학과"
        ]
      }
    ]
  },
  {
    "category": "융합학부",
    "depts": [
      {
        "name": "융합학부",
        "majors": [
          "멀티미디어사운드&뮤직",
          "융합학부"
        ]
      }
    ]
  }
];

const subjects = [
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "21세기기업의인재상",
    "code": "40026",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "3D그래픽디자인II",
    "code": "13640",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "3D그래픽디자인II",
    "code": "13640",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "3D디자인Ⅱ",
    "code": "15950",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "4차산업혁명과물리학",
    "code": "15090",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "AI스마트미디어광고",
    "code": "13337",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "AI스마트인증워크숍",
    "code": "14635",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "AI시대광고캠페인과IMC전략",
    "code": "10211",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "AI시대미디어정책과사례",
    "code": "12657",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "APEX 101",
    "code": "14897",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "APEX 102",
    "code": "14898",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "APEX 201",
    "code": "14899",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "APEX 202",
    "code": "14900",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Advanced English Conversation",
    "code": "14982",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "American Culture Through Movie",
    "code": "14983",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Basic Chinese for Tourism and Travel",
    "code": "15878",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "Business CommunicationⅡ",
    "code": "13613",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "Business WritingⅡ",
    "code": "13090",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "C#프로그래밍",
    "code": "12447",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Class Piano Ⅱ",
    "code": "10030",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "Commercial English",
    "code": "11998",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "ESG경영",
    "code": "15588",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "English Interview Strategy",
    "code": "14494",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "English Topic Discussion ll",
    "code": "13837",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "English Writing",
    "code": "14913",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "English in Social Welfare",
    "code": "15934",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "English through the Bible",
    "code": "15443",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "Grammar for Writing Ⅱ",
    "code": "14504",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "High-Tech 메이커 섬유패션디자인",
    "code": "14739",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "ICT취창업론",
    "code": "15350",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Introduction to Worship",
    "code": "15874",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "IoT와인공지능",
    "code": "14659",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "KOICA&관광ODA",
    "code": "15834",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Korean Tourism",
    "code": "15265",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "Listening Strategy 102",
    "code": "12756",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "OTT시대의미디어비평",
    "code": "10671",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "PR개론",
    "code": "11724",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "R&D보안론",
    "code": "14555",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "SNS비지니스의이해",
    "code": "13302",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "Social Media Marketing",
    "code": "15266",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "Speaking PracticeⅡ",
    "code": "14707",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "Virtual패션Ⅱ",
    "code": "15951",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "World News and Issues",
    "code": "14884",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "e-비즈니스론",
    "code": "12668",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "가족복지론",
    "code": "10064",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "가족상담의이론과실천",
    "code": "15862",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "간호관리학Ⅱ",
    "code": "13851",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "간호관리학실습",
    "code": "13850",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "간호정책과리더십",
    "code": "15251",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "간호학연구",
    "code": "13493",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "객체지향개발론",
    "code": "15718",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "거시경제",
    "code": "10076",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "건강상담과심리",
    "code": "13245",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "건반음악문헌Ⅱ",
    "code": "12196",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "건반화성Ⅱ",
    "code": "10079",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "건반화성Ⅱ",
    "code": "10079",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "경영전략",
    "code": "13630",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰과법률",
    "code": "15341",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰무도",
    "code": "13091",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰수사론",
    "code": "10902",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰영어Ⅱ",
    "code": "14476",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰학개론II",
    "code": "13756",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰행정법Ⅱ",
    "code": "12523",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "경찰행정법연습",
    "code": "15244",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "고급영문해석연구",
    "code": "14885",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "고급화성학의이론과실습Ⅱ",
    "code": "14719",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "공간CADⅡ",
    "code": "13097",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "공간조형",
    "code": "13101",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "공간코디네이션",
    "code": "13107",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "공공예술과문화ODA",
    "code": "15176",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "공공환경디자인",
    "code": "14322",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "공연기획과제작Ⅱ",
    "code": "15235",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "공연예술전공탐색세미나",
    "code": "15880",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "공연창작실습Ⅱ",
    "code": "15701",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "과학수사론",
    "code": "14233",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광경제학",
    "code": "15849",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광레저",
    "code": "14318",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광법규",
    "code": "10146",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광서비스마케팅",
    "code": "12694",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광엔터테인먼트",
    "code": "14847",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광인적자원관리",
    "code": "15041",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광일본어",
    "code": "13585",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광자원론",
    "code": "10153",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광지조사논문",
    "code": "12101",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광한국사문화해설",
    "code": "14563",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "관광현업실습Ⅱ",
    "code": "12688",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관악합주Ⅱ",
    "code": "10173",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관악합주Ⅳ",
    "code": "10175",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관악합주Ⅵ",
    "code": "10177",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관악합주Ⅷ",
    "code": "10179",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현악교수학Ⅱ",
    "code": "15856",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현악법Ⅱ",
    "code": "12199",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "관현악법Ⅱ",
    "code": "12199",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현합주Ⅱ",
    "code": "12583",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현합주Ⅳ",
    "code": "12585",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현합주Ⅵ",
    "code": "12587",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "관현합주Ⅷ",
    "code": "12589",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "광고프리젠테이션",
    "code": "11580",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "교단헌법",
    "code": "10228",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "교양산책",
    "code": "14978",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "국내관광지답사",
    "code": "13763",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "국제영화제워크숍",
    "code": "14588",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "국제통상이론과실재",
    "code": "14240",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "그래픽디자인사",
    "code": "12818",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "글로벌경영",
    "code": "14731",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "글로벌관광상품개발",
    "code": "15340",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "글로벌미디어광고워크숍",
    "code": "15846",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "기독교교육",
    "code": "10337",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "기본간호학Ⅱ",
    "code": "13564",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "기본간호학실습Ⅱ",
    "code": "13565",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "기술사업계획서종합설계",
    "code": "14917",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "기업가정신과창업Ⅱ",
    "code": "14342",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "기원의사회·문화사",
    "code": "15990",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "기초문장해석연습",
    "code": "14706",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "기초수학",
    "code": "15077",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "기초연기Ⅱ",
    "code": "13044",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "기초움직임과표현",
    "code": "13802",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "기초음악이론및실습",
    "code": "13797",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "기초중국어",
    "code": "15595",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "기초한영통역",
    "code": "14360",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "네트워크보안",
    "code": "12178",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "네트워크보안",
    "code": "12811",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "노동과인권",
    "code": "15414",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "노래와연기발성기술",
    "code": "15035",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "노인복지론",
    "code": "10441",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "논리로보는세상",
    "code": "10442",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "놀이치료II",
    "code": "15729",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "농구지도론",
    "code": "14336",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "다문화사회와문화다양성",
    "code": "15260",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "다문화사회의이해",
    "code": "14672",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "대위법의이론과실습Ⅱ",
    "code": "14727",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "데이터분석과활용A",
    "code": "15592",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "데이터분석과활용B",
    "code": "15598",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "데이터분석과활용C",
    "code": "15599",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "데이터통신",
    "code": "10473",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "데이터해석과응용",
    "code": "15871",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "도시농업의재배기술",
    "code": "15171",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "도시생활과힐링원예",
    "code": "15170",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "독립연구",
    "code": "14854",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "독어딕션Ⅱ",
    "code": "10484",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "드라마로배우는중국어",
    "code": "15786",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "드라마영화연기Ⅱ",
    "code": "15040",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "드레이핑",
    "code": "12402",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "드론코딩및실습",
    "code": "15118",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "디자인학부",
    "year": 1,
    "name": "디자인모티브",
    "code": "15963",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "디자인씽킹과창업",
    "code": "14918",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "디자인학부",
    "year": 1,
    "name": "디자인이야기",
    "code": "15959",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "디자인컴퓨터드로잉",
    "code": "15939",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "디자인하는대화의기술",
    "code": "15091",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "디지털그래픽스Ⅱ",
    "code": "15944",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "디지털마케팅전략",
    "code": "14433",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "디지털미디어리터러시",
    "code": "15259",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "디지털일러스트레이션Ⅱ",
    "code": "12820",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "디지털일러스트레이션Ⅱ",
    "code": "12820",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "디지털포렌식 Ⅱ",
    "code": "15446",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "디지털포토그라피",
    "code": "12262",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "디지털포토그라피",
    "code": "12262",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "딥러닝기초",
    "code": "15178",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "딥러닝이론및실습",
    "code": "15470",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "딥러닝코딩",
    "code": "15791",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "리눅스실습",
    "code": "12176",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "마케팅관리론",
    "code": "12665",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "멀티미디어공학",
    "code": "12169",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "멀티미디어사운드&뮤직",
    "code": "15669",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "멘토와멘토링",
    "code": "14784",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "모세오경",
    "code": "10582",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "목공실습",
    "code": "14843",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "몸철학과연극의역사",
    "code": "15080",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "무대기술제작실습Ⅱ",
    "code": "13795",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "무대조명과음향의이해Ⅱ",
    "code": "15234",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "문명의창조와전달",
    "code": "15071",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "문자디자인과전각",
    "code": "13325",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "문학이해와감상",
    "code": "14901",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "문화예술교육현장의이해와실습",
    "code": "14517",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "문화의빅뱅,그리고콘텐츠",
    "code": "15074",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "문화읽기와글쓰기",
    "code": "14252",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "물류ERP",
    "code": "12674",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬공연제작실습Ⅱ",
    "code": "13798",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬공연제작실습Ⅳ",
    "code": "13804",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬넘버의분석Ⅱ",
    "code": "13533",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬댄스Ⅱ",
    "code": "13535",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬댄스Ⅳ",
    "code": "13801",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬보컬연구및실연Ⅱ",
    "code": "15038",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬사",
    "code": "13423",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬연기테크닉실습Ⅱ",
    "code": "15703",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬예술경영입문Ⅱ",
    "code": "13805",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "뮤지컬오디션실습Ⅱ",
    "code": "15704",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "뮤지컬음악과장면구현",
    "code": "15998",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "미디어경영",
    "code": "13347",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "미디어광고현장실무",
    "code": "15845",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "미디어를통해본일본",
    "code": "14909",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "미디어영상졸업작품제작",
    "code": "15844",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "미디어영상캡스톤디자인",
    "code": "15843",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "미디어와사회",
    "code": "12746",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "미술과인간심리",
    "code": "15072",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "바울서신",
    "code": "10639",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "반주법Ⅱ",
    "code": "15708",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "발레Ⅱ",
    "code": "12348",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "방과후교육현장실습",
    "code": "13815",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "배드민턴지도론",
    "code": "13310",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "백엔드웹개발",
    "code": "15180",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "범죄심리학기초",
    "code": "13095",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "범죄예방론",
    "code": "14326",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "범죄학개론",
    "code": "12521",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "법과사회",
    "code": "10793",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "보건의료법규",
    "code": "13849",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "부가가치세회계",
    "code": "14393",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "불어딕션Ⅱ",
    "code": "10721",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "브랜드와디자인의보호",
    "code": "13637",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "브랜드저널리즘",
    "code": "14787",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "브랜드패키지디자인실무",
    "code": "13778",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "비교경찰제도론",
    "code": "10724",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "비판적사고와간호과정",
    "code": "13243",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "빅데이터R프로그래밍",
    "code": "15723",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "빅데이터분석및시각화",
    "code": "15181",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "빅데이터응용시스템",
    "code": "15732",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "빅데이터의이해",
    "code": "14906",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "사군자이론과실습",
    "code": "13322",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사례관리론",
    "code": "15239",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "사운드디자인및제작",
    "code": "15600",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "사운드디자인및제작",
    "code": "15600",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회문제론",
    "code": "10754",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회보장론",
    "code": "10755",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지법제와실천",
    "code": "10759",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지실천기술론",
    "code": "10762",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지역사",
    "code": "10756",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지와문화다양성",
    "code": "15238",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지와인권",
    "code": "15237",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지특별세미나",
    "code": "13264",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회복지현장실습",
    "code": "13265",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "사회봉사와진로탐색Ⅱ",
    "code": "13263",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "사회봉사이론과실제Ⅱ",
    "code": "10781",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "산업보안관리캡스톤디자인실습",
    "code": "15047",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "산업보안윤리",
    "code": "14548",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "산업보안정책",
    "code": "14553",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "산업보안컨설팅Ⅱ",
    "code": "15045",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "산업보안판례연구",
    "code": "14658",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "산업복지론",
    "code": "10784",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "산학연계형중국어캡스톤디자인",
    "code": "15575",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "융합학부",
    "year": 1,
    "name": "산학협동화과정",
    "code": "15989",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "상담심리학",
    "code": "14879",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "생산관리",
    "code": "10791",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "생활독일어",
    "code": "14922",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "생활속의정보통신기술활용전략",
    "code": "15438",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "생활속의회계",
    "code": "14451",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "생활중국어회화",
    "code": "15693",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "서양미술사",
    "code": "14452",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "서양역사와문화",
    "code": "15836",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "서양음악사Ⅱ",
    "code": "10814",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "설교신학",
    "code": "15864",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "성격심리학",
    "code": "14040",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "성악교수학Ⅱ",
    "code": "15859",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "성악문헌Ⅱ",
    "code": "10879",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "성인건강간호학Ⅰ",
    "code": "13268",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "성인건강간호학Ⅲ",
    "code": "13567",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "성인건강간호학Ⅴ",
    "code": "13843",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "성인건강간호학실습Ⅱ",
    "code": "13571",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "성인건강간호학실습Ⅳ",
    "code": "13844",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "세계교회사",
    "code": "10883",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "세계오순절운동사",
    "code": "10890",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "세계의지역분쟁",
    "code": "15873",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "세무회계연습",
    "code": "12788",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "셉테드경비공학",
    "code": "15440",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "소비자행동분석",
    "code": "10895",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "소재기획및소싱실무",
    "code": "13439",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "스마트공장수준컨설팅",
    "code": "15441",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "스마트콘텐츠제작실습",
    "code": "14362",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "시가·지혜서",
    "code": "15865",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "시창,청음Ⅱ",
    "code": "10927",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "식음료와문화II",
    "code": "13336",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "신앙과섬김",
    "code": "15593",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "신약입문",
    "code": "15866",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "실내건축스튜디오Ⅱ",
    "code": "15946",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "실내건축스튜디오Ⅳ",
    "code": "15948",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "실무일본어",
    "code": "14926",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "실용재즈반주Ⅱ",
    "code": "13072",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "실용재즈반주Ⅱ",
    "code": "13072",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "실용중국어",
    "code": "14920",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "실용중국어회화",
    "code": "14371",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "심리진단및평가",
    "code": "14872",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "심화피아노연주법Ⅱ",
    "code": "15474",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "심화피아노연주법Ⅳ",
    "code": "15472",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "아나운싱과내레이션",
    "code": "13342",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "아동간호학Ⅱ",
    "code": "13705",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "아동간호학실습",
    "code": "13574",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "아동발달",
    "code": "14881",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "아동복지론",
    "code": "11017",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "아이덴티티디자인",
    "code": "15972",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "악기론Ⅱ",
    "code": "14220",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "악기집중탐구Ⅱ",
    "code": "10705",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "악기집중탐구Ⅳ",
    "code": "10707",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "양성평등적성의이해",
    "code": "12277",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "여성건강간호학Ⅰ",
    "code": "13491",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "여성건강간호학Ⅲ",
    "code": "15713",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "여성복지론",
    "code": "11045",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "여행중국어회화",
    "code": "15694",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "연주Ⅰ",
    "code": "11059",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "연주Ⅱ",
    "code": "11060",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "연주Ⅳ",
    "code": "11062",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "연주Ⅵ",
    "code": "11064",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "영미문학과문화의스토리텔링",
    "code": "15779",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "영산목회실습",
    "code": "12615",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "영상디자인",
    "code": "13341",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "영상디자인",
    "code": "13341",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "영상미디어번역",
    "code": "14493",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "영상으로 읽는 미국문화",
    "code": "15591",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "영상편집활용SKILL",
    "code": "15060",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "영양과식이",
    "code": "13271",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "영어딕션Ⅱ",
    "code": "11101",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "영화로이해하는중국근현대사",
    "code": "14688",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "영화를통해본과학",
    "code": "13811",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "영화영상으로읽는패션",
    "code": "15107",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "예배학",
    "code": "11129",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "예술경영공연기획실무",
    "code": "15793",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "예언서",
    "code": "11133",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "오디션연기실습Ⅱ",
    "code": "15706",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "오페라클래스Ⅱ",
    "code": "11155",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "오페라클래스Ⅳ",
    "code": "11157",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "오픈소스기반소프트웨어개발캡스톤디자인",
    "code": "15231",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "외식경영론",
    "code": "14849",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "운영체제",
    "code": "11164",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "웹보안",
    "code": "13602",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "웹프로그래밍",
    "code": "13520",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "IT학부",
    "year": 1,
    "name": "웹프로그래밍",
    "code": "15905",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "웹프로그래밍",
    "code": "15905",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "유럽사회와인간",
    "code": "14923",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "IT학부",
    "year": 1,
    "name": "융합보안개론",
    "code": "15904",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "융합적사고와글쓰기",
    "code": "14462",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악&사운드소프트웨어실습Ⅱ",
    "code": "12576",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "음악&사운드소프트웨어실습Ⅱ",
    "code": "12576",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악감상과이해",
    "code": "15861",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악교수학습방법",
    "code": "14519",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악교육프로그램개발",
    "code": "14518",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악분석Ⅱ",
    "code": "13793",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "음악으로보는서양건축",
    "code": "11819",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악이태리어Ⅱ",
    "code": "11233",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "음악치료입문",
    "code": "11218",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "응급재해간호",
    "code": "14845",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "의료사회복지론",
    "code": "11221",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "이노베이션패키징Ⅱ",
    "code": "14340",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "인간심리의이해",
    "code": "12039",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "인간행동과사회환경",
    "code": "11246",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "인공지능과스마트HTML제작",
    "code": "14641",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "인문학으로보는성공경영",
    "code": "15879",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "인성과리더쉽",
    "code": "15582",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "인체생리학",
    "code": "13123",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "",
    "major": "",
    "year": 1,
    "name": "인터넷과지식재산권법",
    "code": "40024",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "임베디드시스템",
    "code": "15232",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "임상약리학",
    "code": "13269",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "자료구조",
    "code": "14549",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "작곡및영상세미나Ⅱ",
    "code": "14721",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "작곡및영상세미나Ⅱ",
    "code": "14721",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "작곡및영상세미나Ⅳ",
    "code": "14723",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "작곡및영상세미나Ⅵ",
    "code": "14725",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "",
    "major": "",
    "year": 1,
    "name": "장기현장실습Ⅰ",
    "code": "14415",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "장애아동이해",
    "code": "14867",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "장애이해를통한공존문화만들기",
    "code": "15094",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "재무관리",
    "code": "11302",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "재무제표분석",
    "code": "12787",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "재테크와자기설계",
    "code": "12224",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "저널리즘의이론과실전",
    "code": "13346",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "전공실기Ⅱ",
    "code": "11308",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "전공실기Ⅱ",
    "code": "11308",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "전공실기Ⅳ",
    "code": "11310",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "전공실기Ⅳ",
    "code": "11310",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "전공실기Ⅴ",
    "code": "11311",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "전공실기Ⅵ",
    "code": "11312",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "전공실기Ⅵ",
    "code": "11312",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "전공실기Ⅶ",
    "code": "11313",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "전공실기Ⅷ",
    "code": "11314",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "미디어영상광고학과",
    "year": 1,
    "name": "전공탐색세미나",
    "code": "15839",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "전시디자인",
    "code": "11327",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "정보시각디자인기법",
    "code": "15690",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "정신건강간호학Ⅱ",
    "code": "13569",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "정신건강간호학실습Ⅱ",
    "code": "13573",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "정의란무엇인가?",
    "code": "14979",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "조명계획",
    "code": "11362",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "조직행동론",
    "code": "11370",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "졸업심사Ⅱ",
    "code": "11932",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "졸업작품심사",
    "code": "13131",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "졸업작품심사및커리어개발Ⅱ",
    "code": "14569",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "졸업전시",
    "code": "11754",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "졸업프로젝트II",
    "code": "13591",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "졸업프로젝트Ⅱ",
    "code": "12529",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "종교개혁사",
    "code": "15869",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "종교에기반한범죄자교정교화",
    "code": "14463",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "종합실습",
    "code": "13848",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "중국4차산업의 이해Ⅰ",
    "code": "15476",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "중국문학작품강독",
    "code": "15783",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "중국비즈니스와문화의이해",
    "code": "15274",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "중국어Ⅰ",
    "code": "13719",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "중국어Ⅱ",
    "code": "13775",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "중국어듣기연습",
    "code": "15699",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "중국어프리젠테이션Ⅱ",
    "code": "14685",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "중급연기Ⅱ",
    "code": "13049",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "중급회계",
    "code": "11407",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "중동의역사와문화",
    "code": "15877",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "중환자간호",
    "code": "15250",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "즉흥연주와작곡",
    "code": "14402",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "증권시장론",
    "code": "11409",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "지구를식히는상상력:기후변화뛰어넘기",
    "code": "15078",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "지구환경과생태",
    "code": "12237",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "지식재산권법II",
    "code": "14390",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "지역사회간호학Ⅱ",
    "code": "13845",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "지역사회간호학실습Ⅱ",
    "code": "13846",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "지역사회복지론",
    "code": "11414",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "지휘법Ⅱ",
    "code": "14844",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "진로집중탐구",
    "code": "13820",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "진로탐색",
    "code": "15257",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "집단심리재활이론및실습",
    "code": "14874",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "창업과경영",
    "code": "13769",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "창업과사회적경제",
    "code": "13814",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "창업보육매니지먼트",
    "code": "14981",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "창의와소통",
    "code": "15253",
    "type": "교양필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "채플",
    "code": "11423",
    "type": "채플",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "채플",
    "code": "11424",
    "type": "채플",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "채플과섬김",
    "code": "15782",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "채플콰이어Ⅱ",
    "code": "13828",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "철학과삶",
    "code": "14251",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "융합학부",
    "year": 1,
    "name": "청소년기관현장실습",
    "code": "15956",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "사회복지학과",
    "year": 1,
    "name": "청소년복지론",
    "code": "11431",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "청소년서비스러닝실습",
    "code": "15444",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "청소년심리및상담",
    "code": "14795",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "청소년육성제도론",
    "code": "14677",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "융합학부",
    "year": 1,
    "name": "청소년지도방법론",
    "code": "14871",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "융합학부",
    "year": 1,
    "name": "청소년프로그램개발과평가",
    "code": "14794",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "체력검정실습",
    "code": "13616",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "체력증진및다이어트운동법",
    "code": "13018",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "초급중국어",
    "code": "13772",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "출판편집디자인실무",
    "code": "13779",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "취업과진로설계Ⅱ",
    "code": "14928",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "취창업특강/현장학습Ⅰ",
    "code": "14626",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "취창업특강/현장학습Ⅱ",
    "code": "14988",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "치료레크리에이션",
    "code": "15089",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "캡스톤디자인 : 머천다이징",
    "code": "14853",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "캡스톤디자인:서스테이너블패션",
    "code": "13581",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "캡스톤디자인:패션디자인스튜디오Ⅱ",
    "code": "12400",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "컴퓨터개론",
    "code": "15903",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "IT학부",
    "year": 1,
    "name": "컴퓨터개론",
    "code": "15903",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "컴퓨터구조론",
    "code": "12446",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "컴퓨터그래픽응용",
    "code": "15965",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "컴퓨터네트워크",
    "code": "14550",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "컴퓨터프로그래밍Ⅱ",
    "code": "15051",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "콘서트콰이어Ⅱ",
    "code": "11496",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "콘서트콰이어Ⅳ",
    "code": "11498",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "콘서트콰이어Ⅵ",
    "code": "11500",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "콘서트콰이어Ⅷ",
    "code": "11502",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "콘텐츠디자인실무",
    "code": "13780",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "콘텐츠디자인실무",
    "code": "13780",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "크리스천리더십",
    "code": "13213",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "크리스천의사회정의",
    "code": "15255",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "크리에티브 테크니컬 스튜디오Ⅱ",
    "code": "12462",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "클라우드컴퓨팅",
    "code": "13364",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "타악기연주법Ⅱ",
    "code": "15709",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "타이포그라피레이아웃",
    "code": "11513",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "테니스지도론",
    "code": "13308",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "테러학",
    "code": "14654",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "중국어학과",
    "year": 1,
    "name": "테마로배우는중국문화Ⅰ",
    "code": "13773",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "토익Ⅱ",
    "code": "13404",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "토탈피트니스",
    "code": "15442",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "통계로읽는사회",
    "code": "15075",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "언어학부",
    "major": "영어학과",
    "year": 1,
    "name": "통역의활용",
    "code": "14497",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "통합보안관제",
    "code": "15448",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "통합시뮬레이션실습Ⅱ",
    "code": "13847",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "통합예술교육의실제",
    "code": "14591",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "트라우마가족치료",
    "code": "15754",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "트레이닝실습지도론",
    "code": "15092",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "트렌드일러스트레이션실무",
    "code": "15184",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "특별사법경찰론",
    "code": "15838",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "패션디지털스튜디오",
    "code": "12562",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "섬유패션디자인학과",
    "year": 1,
    "name": "패션마케팅",
    "code": "13440",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "패션테크놀로지",
    "code": "15095",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "시각정보디자인학과",
    "year": 1,
    "name": "편집디자인Ⅱ",
    "code": "11541",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "평생학습사회와미디어",
    "code": "15158",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "디자인학부",
    "major": "실내건축디자인학과",
    "year": 1,
    "name": "프로페셔널포트폴리오",
    "code": "15941",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "컴퓨터공학과",
    "year": 1,
    "name": "프론트엔드개발",
    "code": "15179",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "피아노교수학Ⅱ",
    "code": "12611",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "피아노실내악앙상블Ⅱ",
    "code": "11589",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "피아노실내악앙상블Ⅳ",
    "code": "12286",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "하모니네이션앙상블지도법Ⅱ",
    "code": "15175",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "학습심리학",
    "code": "14868",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "한국역사와문화",
    "code": "11622",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "한문속의중국문화",
    "code": "13810",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "합창Ⅱ",
    "code": "11652",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "합창Ⅱ",
    "code": "12249",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "합창Ⅳ",
    "code": "11654",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "IT학부",
    "major": "융합보안학과",
    "year": 1,
    "name": "항공보안",
    "code": "14554",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "항공서비스",
    "code": "15936",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "항공예약실무론",
    "code": "12690",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "헌법Ⅰ",
    "code": "11665",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "헬라어",
    "code": "11667",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "현대무용실습Ⅱ",
    "code": "13058",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "현대무용실습Ⅳ",
    "code": "13800",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "현대사회와종교",
    "code": "10352",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "현대사회의부모되기교육",
    "code": "14744",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "교양학부",
    "major": "교양학부",
    "year": 1,
    "name": "현대사회적성의패러다임전환",
    "code": "15076",
    "type": "교양선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "현악합주Ⅱ",
    "code": "11706",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "현악합주Ⅳ",
    "code": "11708",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "현악합주Ⅵ",
    "code": "11710",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "현악합주Ⅷ",
    "code": "11712",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "형법각론",
    "code": "11713",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "형법연습",
    "code": "12283",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "공공서비스학부",
    "major": "경찰행정학과",
    "year": 1,
    "name": "형사소송법Ⅱ",
    "code": "12642",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "관광경영학과",
    "year": 1,
    "name": "호텔커뮤니케이션",
    "code": "11986",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "융합학부",
    "major": "멀티미디어사운드&뮤직",
    "year": 1,
    "name": "화성학II",
    "code": "12579",
    "type": "전공필수",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "음악학과",
    "year": 1,
    "name": "화성학II",
    "code": "12579",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "예술학부",
    "major": "공연예술학과",
    "year": 1,
    "name": "화술테크닉Ⅱ",
    "code": "15469",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "환경경영",
    "code": "11730",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "신학과",
    "major": "신학과",
    "year": 1,
    "name": "환경신학",
    "code": "15868",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "간호학과",
    "major": "간호학과",
    "year": 1,
    "name": "환자안전",
    "code": "15711",
    "type": "전공선택",
    "credit": 3,
    "cap": 30,
    "prof": ""
  },
  {
    "dept": "사회과학부",
    "major": "경영학과",
    "year": 1,
    "name": "회계원리",
    "code": "11733",
    "type": "전공기초",
    "credit": 3,
    "cap": 30,
    "prof": ""
  }
];